Models/ErrorViewModel.cs
namespace Portal.Web.App.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/News.cs
using System.ComponentModel.DataAnnotations;
using System.Security.Principal;

namespace Portal.Web.App.Models
{
    public class News
    {
        [Key]
        public int NewsId { get; set; }
        [Display(Name ="News Title")]
        [Required]
        public string Title { get; set; }
        [Display(Name ="Content")]
        public string Body { get; set; }
        [Display(Name = "Image")]
        public string? Image { get; set; } = "Defoult.png";
        [Display(Name = "Posted Date")]
        public DateTime PostDate { get; set; }= DateTime.Now;
        [Display(Name = "Posted By")]
        public string PostedBy { get; set; }
    }
}

Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace Portal.Web.App.Models
{
    public class User
    {
        public int Id { get; set; }
        public string Fullname { get; set; }
        [Display(Name = "User Name")]
        [DataType(DataType.Text)]
        [Required]
        public string Username { get; set; }
        [Display(Name ="User Password")]
        [DataType(DataType.Password)]
        [Required]
        public string Password { get; set; }
    }
}

ViewModels/NewsViewModel.cs
using Portal.Web.App.Models;

namespace Portal.Web.App.ViewModels
{
    public class NewsViewModel
    {
        public News News { get; set; }
        public IEnumerable<News> NewsList { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Portal.Web.App.Models;
using System.Diagnostics;

namespace Portal.Web.App.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Portal.Web.App.Data;
using Portal.Web.App.Models;
using Portal.Web.App.ViewModels;

namespace Portal.Web.App.Controllers
{
    public class NewsController : Controller
    {
        private readonly NewsContext _context;

        public NewsController(NewsContext context)
        {
            _context = context;
        }

        // GET: News
        public async Task<IActionResult> Manage(int? id,bool? mode=false)
        {
                      
            ViewBag.IsAddNew = mode;
            

            var model = new NewsViewModel();
            model.NewsList = await _context.News.ToListAsync();
            if (id > 0)
            {
                model.News =await _context.News.FindAsync(id);
                ViewBag.IsAddNew = true;

            }
            else
            {
                model.News = new News();
            }

            return View(model);
        }

        public async Task<IActionResult> Index()
        {
            var data = await _context.News.ToListAsync();

            return View(data.OrderByDescending(a=>a.PostDate).Take(2));
        }

        // GET: News/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News
                .FirstOrDefaultAsync(m => m.NewsId == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        // GET: News/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: News/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NewsId,Title,Body,Image,PostDate,PostedBy")] News news)
        {
            if (ModelState.IsValid)
            {
                if(news.NewsId > 0)
                {
                    var updata= await _context.News.FindAsync(news.NewsId);
                    if(updata != null)
                    {
                        updata.PostDate = DateTime.Now;

                        if (updata.Title != news.Title)
                            updata.Title = news.Title;

                        if (updata.PostedBy != news.PostedBy)
                            updata.PostedBy = news.PostedBy;

                        if(updata.Body != news.Body)
                            updata.Body = news.Body;

                        _context.News.Update(updata);
                        await _context.SaveChangesAsync();

                    }
                }
                else
                {
                    _context.Add(news);
                    await _context.SaveChangesAsync();
                }
                
                return RedirectToAction(nameof(Manage));
            }
            return View("Manage");
        }

        // GET: News/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News.FindAsync(id);
            if (news == null)
            {
                return NotFound();
            }
            return View(news);
        }

        // POST: News/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NewsId,Title,Body,Image,PostDate,PostedBy")] News news)
        {
            if (id != news.NewsId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(news);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NewsExists(news.NewsId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Manage));
            }
            return View("Manage");
        }

        // GET: News/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News
                .FirstOrDefaultAsync(m => m.NewsId == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        // POST: News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var news = await _context.News.FindAsync(id);
            if (news != null)
            {
                _context.News.Remove(news);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NewsExists(int id)
        {
            return _context.News.Any(e => e.NewsId == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome Haile</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/News/Create.cshtml
@model Portal.Web.App.Models.News

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>News</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Body" class="control-label"></label>
                <input asp-for="Body" class="form-control" />
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostDate" class="control-label"></label>
                <input asp-for="PostDate" class="form-control" />
                <span asp-validation-for="PostDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostedBy" class="control-label"></label>
                <input asp-for="PostedBy" class="form-control" />
                <span asp-validation-for="PostedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/News/Delete.cshtml
@model Portal.Web.App.Models.News

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>News</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Body)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Body)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostedBy)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="NewsId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/News/Details.cshtml
@model News

@{
    ViewData["Title"] = "Details";
}
<div class="col">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-3">
                    <img src="~/Asset/@Model.Image" class="img-thumbnail" />

                </div>
                <div class="col-7">
                    <h4 class="">@Model.Title</h4>
                </div>
            </div>
        </div>
        <div class="card-body" style="height:300px">
            <p>
                @Model.Body
            </p>

        </div>
        <div class="card-footer">
            <p>Posted By : <b>@Model.PostedBy</b></p>
            <p>Posted Date : <b>@Model.PostDate</b></p>
        </div>
    </div>
    <a asp-action="Index" class="btn btn-info">Back to List</a>
</div>

Views/News/Edit.cshtml
@model Portal.Web.App.Models.News

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>News</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="NewsId" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Body" class="control-label"></label>
                <input asp-for="Body" class="form-control" />
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostDate" class="control-label"></label>
                <input asp-for="PostDate" class="form-control" />
                <span asp-validation-for="PostDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostedBy" class="control-label"></label>
                <input asp-for="PostedBy" class="form-control" />
                <span asp-validation-for="PostedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/News/Index.cshtml
@model IEnumerable<News>

@{
    ViewData["Title"] = "Index";
}

<div class="row">
    @if(Model.Any() || Model != null)
    {
        @foreach(var n in Model)
        {
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-3">
                                <img src="~/Asset/@n.Image" class="img-thumbnail" />
                                
                            </div>
                            <div class="col-7">
                                <h4 class="">@n.Title</h4>
                            </div>
                         </div>   
                    </div>
                    <div class="card-body">
                        <p>
                            @if(n.Body.Length>100){
                                @n.Body.Substring(1, 100) <a asp-action="Details" asp-controller="News"
                                                         asp-route-id="@n.NewsId"
                                                         class="btn btn-outline-primary btn-sm">Read More...</a>
                            }else{
                                @n.Body
                            }
                            
                        </p>
                        
                    </div>
                    <div class="card-footer">
                        <p>Posted By : <b>@n.PostedBy</b></p>
                        <p>Posted Date : <b>@n.PostDate</b></p>
                    </div>
                </div>
            </div>
        }
        
    }
    else
    {
        <h5>No News On Database</h5>
    }

</div>

Views/News/Manage.cshtml
@model NewsViewModel

@{
    ViewData["Title"] = "Manage";
}

<h1>Manage</h1>
@if (ViewBag.IsAddNew== false)
{
    <a class="btn btn-primary" asp-action="Manage" asp-route-mode="true"> Create News</a>

}

@if (ViewBag.IsAddNew)
{
    <div class="row">
        <div class="col-md-12">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="News.NewsId" />
                <div class="form-group">
                    <label asp-for="News.Title" class="control-label"></label>
                    <input asp-for="News.Title" class="form-control" />
                    <span asp-validation-for="News.Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="News.Body" class="control-label"></label>
                    <input asp-for="News.Body" class="form-control" />
                    <span asp-validation-for="News.Body" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="News.Image" class="control-label"></label>
                    <input asp-for="News.Image" class="form-control" />
                    <span asp-validation-for="News.Image" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="News.PostDate" class="control-label"></label>
                    <input asp-for="News.PostDate" class="form-control" />
                    <span asp-validation-for="News.PostDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="News.PostedBy" class="control-label"></label>
                    <input asp-for="News.PostedBy" class="form-control" />
                    <span asp-validation-for="News.PostedBy" class="text-danger"></span>
                </div>
                <div class="form-group">
                    @if (Model.News.NewsId > 0)
                    {
                        <input type="submit" value="Update" class="btn btn-primary" />
                    }
                    else
                    {
                        <input type="submit" value="Create" class="btn btn-primary" />
                    }
                </div>
            </form>
        </div>
    </div>
}



<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.News.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.News.Body)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.News.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.News.PostDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.News.PostedBy)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if(Model!=null && Model.NewsList.Any())
        {
            @foreach (var item in Model.NewsList)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Body)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Image)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PostDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PostedBy)
                    </td>
                    <td>
                        <a asp-action="Manage" asp-route-id="@item.NewsId">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.NewsId">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.NewsId">Delete</a>
                    </td>
                </tr>
            }
        }
        
    </tbody>
</table>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Portal.Web.App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Portal.Web.App.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <a asp-action="Manage" asp-controller="News"
               class="btn btn-success">News Admin Page</a>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Portal.Web.App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>